### ISSUE TITLE
it_should_run_callbacks for validate and Rails 4.1 compatibility

### ISSUE THREAD

**Issue by query-string** [makandra/rspec_candy#3]
Since update to Rails 4.1 it_should_run_callbacks fails with error:

``` bash
1) Gig#validate should run callbacks [:prevent_capacity_change_if_gig_has_occurred]
     Failure/Error: subject.send(callback.filter.to_s.gsub(/[\(,\)]/, '').to_sym) {}
     NoMethodError:
       undefined method `#<ActiveRecord::Validations::PresenceValidator:0x007fc9db6edcd0>' for #<Gig:0x007fc9dafb22b8>
```

My spec looks like:

``` rb
describe "#validate" do
 it_should_run_callbacks(:prevent_capacity_change_if_gig_has_occurred)
end
```

And model:

``` rb
class Gig < ActiveRecord::Base
 validate :prevent_capacity_change_if_gig_has_occurred
 def prevent_capacity_change_if_gig_has_occurred
 end
end
```

**Comment by chip-miller** [comment]
I can verify that this is still a problem in Rails 4.2.  I switched my approach to 'test from a higher level', but it would be nice to have this helper back :)

**Comment by lukasz-wojcik** [comment]
In rails 5.1.3 I have an error as well

`app/models/post.rb`

```ruby
class Post < ApplicationRecord

  before_create :example_callback

  private

  def example_callback
    # ...
  end
end
```
`spec/models/post_spec.rb`

```ruby
require "rails_helper"

describe Post do

  context '#after_create' do
    it_should_run_callbacks :example_callback
  end

end
```

Error:

```

**Comment by triskweline** [comment]
This helper was introduced back in 2010 when we were trying to avoid hitting the database in AR tests because of misguided reasons. I've long since moved on to just calling `valid?` and `save` on my records and see if the desired effect has happened. I encourage everyone to do the same.

Let's just remove this helper. Given that this bug is 4 years old, obviously no one is willing to maintain it through versions of Rails.

**Comment by triskweline** [comment]
Removed in `0.5.0`.
